spring.application.name=ravyn

spring.datasource.url=jdbc:postgresql://localhost:5432/ravyn
spring.datasource.username=julienduclos

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration