spring.application.name=ravyn

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ravyn}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:julienduclos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Spring Security
# Disable Spring Boot's default generated in-memory user because Ravyn manages session auth through AuthService
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration