package com.ravyn.chat.exception;

public enum ErrorCode {
    CONVERSATION_NOT_FOUND,
    USER_NOT_FOUND,
    CONVERSATION_WITH_SELF,
    CORRUPTED_DATA,
    INVALID_CREDENTIALS,
    USERNAME_TAKEN,
    USERNAME_NOT_FOUND,
    AUTHENTICATION_REQUIRED,
    CONVERSATION_ACCESS_DENIED,
    MESSAGE_CONTENT_TOO_LONG,
    EMPTY_MESSAGE_CONTENT,
    ALREADY_AUTHENTICATED,
    AUTHENTICATED_USER_NOT_FOUND,
    VALIDATION_FAILED,
    CONNECTION_WITH_SELF,
    CONNECTION_REQUEST_ALREADY_PENDING,
    INCOMING_CONNECTION_REQUEST_EXISTS,
    ALREADY_CONNECTED,
    CONNECTION_RELATIONSHIP_CONFLICT,
    CONNECTION_REQUEST_NOT_FOUND,
    CONNECTION_REQUEST_ACCESS_DENIED,
    CONNECTION_REQUEST_ALREADY_RESOLVED
}
