package com.ravyn.chat.exception;

public enum ErrorCode {
    CONVERSATION_NOT_FOUND,
    USER_NOT_FOUND,
    CONVERSATION_WITH_SELF,
    CORRUPTED_DATA,
    INVALID_CREDENTIALS,
    USERNAME_TAKEN,
    USERNAME_NOT_FOUND
}
