CREATE TABLE chat_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_chat_user_username UNIQUE (username)
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_low_id BIGINT NOT NULL,
    participant_high_id BIGINT NOT NULL,
    CONSTRAINT fk_conversation_participant_low FOREIGN KEY (participant_low_id) REFERENCES chat_user(id),
    CONSTRAINT fk_conversation_participant_high FOREIGN KEY (participant_high_id) REFERENCES chat_user(id),
    CONSTRAINT chk_conversation_participant_order CHECK (participant_low_id < participant_high_id),
    CONSTRAINT uk_conversation_participants UNIQUE (participant_low_id, participant_high_id)
);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES chat_user(id)
);
