CREATE TABLE chat_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_chat_user_username UNIQUE (username),
    CONSTRAINT chk_chat_user_username_length CHECK (char_length(btrim(username, E' \t\n\r\f\x0B')) BETWEEN 2 AND 20),
    CONSTRAINT chk_display_name_length CHECK (char_length(btrim(display_name, E' \t\n\r\f\x0B')) BETWEEN 2 AND 50)
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_low_id BIGINT NOT NULL,
    participant_high_id BIGINT NOT NULL,
    CONSTRAINT fk_conversation_participant_low FOREIGN KEY (participant_low_id) REFERENCES chat_user(id),
    CONSTRAINT fk_conversation_participant_high FOREIGN KEY (participant_high_id) REFERENCES chat_user(id),
    CONSTRAINT chk_conversation_participant_order CHECK (participant_low_id < participant_high_id),
    CONSTRAINT uk_conversation_participants UNIQUE (participant_low_id, participant_high_id)
);

CREATE INDEX idx_conversation_participant_high_id ON conversation (participant_high_id);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES chat_user(id)
);

CREATE INDEX idx_message_conversation_id_created_at ON message (conversation_id, created_at);
CREATE INDEX idx_message_sender_id ON message (sender_id);

CREATE TABLE conversation_read_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversation_read_state_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_read_state_user FOREIGN KEY (user_id) REFERENCES chat_user(id) ON DELETE CASCADE,
    CONSTRAINT uk_conversation_read_state_conversation_user UNIQUE (conversation_id, user_id)
);

CREATE TABLE connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_sender_id BIGINT NOT NULL,
    request_receiver_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_connection_sender FOREIGN KEY (request_sender_id) REFERENCES chat_user(id),
    CONSTRAINT fk_connection_receiver FOREIGN KEY (request_receiver_id) REFERENCES chat_user(id),
    CONSTRAINT chk_connection_not_self CHECK (request_sender_id != request_receiver_id),
    CONSTRAINT chk_connection_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT chk_connection_resolution CHECK (
            (status = 'PENDING' AND resolved_at IS NULL)
                OR
            (status IN ('ACCEPTED', 'REJECTED') AND resolved_at IS NOT NULL)
            ));

CREATE UNIQUE INDEX uk_connection_users
    ON connection (
                   LEAST(request_sender_id, request_receiver_id),
                   GREATEST(request_sender_id, request_receiver_id)
        );
CREATE INDEX idx_connection_incoming_pending ON connection(request_receiver_id) WHERE status = 'PENDING';
CREATE INDEX idx_connection_sender_status ON connection(request_sender_id, status);
CREATE INDEX idx_connection_receiver_status ON connection(request_receiver_id, status);
